### PR TITLE
[FIX] Fixed Messages and Added SNS Events for Closing Session after Escalation.

### LINKED ISSUE #1278: [BUG] [Chat End Logging] Fix "Conversation closed:" logging as seen in a chat session transcript for escalated sessions
Currently the "Conversation closed" message is not always accurate.  

For example, in an escalated session all Conversation closed messages show "Chat ended by visitor", even if the chat was actually closed by the agent, or timed out. 
https://github.com/WideChat/Apps.Salesforce.LiveAgent/blob/master/helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/HandleEndChatCallback.ts#L62

We need to properly define all the reasons while closing rooom. visitor, agent, session expired etc.  We should verify for both escalated and non escalated sessions. 

As a side note: our SNS event logging for chat closed needs to be accurate as well...

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
Fixes: https://github.com/WideChat/Rocket.Chat/issues/1278

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis I tested this and it looks good.
@csmith14 can you review please?  thanks...

**Review by csmith14 — APPROVED** [review]
Tested and looks good to me!

**Review by Shailesh351 — COMMENTED** [review]
I just found that `Closed by agent` will be used also for other reasons for chat being closed. i.e. Session expiration, or any other App/network error.

`Closed by agent` should be set only when the chat is actually ended by the salesforce agent. which is when we receive `ChatEnded` with reason `agent` from salesforce
https://github.com/WideChat/Apps.Salesforce.LiveAgent/blob/master/helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts#L64...L73

We should keep other message for other errors

**Comment by ear-dev** [comment]
Thanks @Shailesh351 If I understand this correctly, we are currently catching a few network errors like, 403, 204, an 409, but anything else gets caught in `closed by agent`.  So the fix is to specifically check for the SF flag "reason==agent" in another 'else if' statement.  Is that your suggestion?

**Comment by Shailesh351** [comment]
> Thanks @Shailesh351 If I understand this correctly, we are currently catching a few network errors like, 403, 204, an 409, but anything else gets caught in `closed by agent`. So the fix is to specifically check for the SF flag "reason==agent" in another 'else if' statement. Is that your suggestion?

Yes...

**Comment by AlexanderKanakis** [comment]
@Shailesh351 A small clarification: We need events for the rest of the statues codes?

**Comment by Shailesh351** [comment]
@AlexanderKanakis Not exactly error codes, It should set message for whatever reason it was closed. If it was closed by some error it should show that error.

File: enum/CloseMessages.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export enum CloseMessages {
+	CLOSED_BY_AGENT = 'Closed by agent',
+	CLOSED_BY_VISITOR = 'Closed by visitor',
+	CLOSED_DUE_TO_TIMEOUT = 'Chat closed due to timeout',
```
Comment (Shailesh351) [inline enum/CloseMessages.ts]: For consistency, can we change `Closed by agent` and `Closed by visitor` to `Chat closed by agent` `Chat closed by visitor`

File: enum/Analytics.ts [hunk 2]
```diff
@@ -8,6 +8,9 @@ export enum EventName {
 	AGENT_TRANSFER_SUCCESSFUL = 'agent_transfer_successful',
 	CHAT_CLOSED_BY_AGENT = 'chat_closed_by_agent',
 	CHAT_CLOSED_BY_TIMEOUT = 'chat_closed_by_timeout',
+	LIVEAGENT_SESSION_EXPIRED = 'live_agent_sesstion_expired',
```
Comment (Shailesh351) [inline enum/Analytics.ts]: Spelling mistake here `sesstion`.

Also, can we add the `CHAT_CLOSED` prefix for these new events? So that it's clear that the actual event that is being sent is the chat closed event

File: enum/Analytics.ts [hunk 3]
```diff
@@ -77,4 +80,28 @@ export const Events: Record<string, IAnalyticsEvent> = {
...
+		eventType: EventType.SESSION,
+		action: 'closed',
+		properties: {
+			close_method: 'expired_session',
+		},
+	},
+	[EventName.UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE]: {
+		category: EventCatagory.CHAT_SESSION,
+		eventType: EventType.SESSION,
+		action: 'failed',
```
Comment (Shailesh351) [inline enum/Analytics.ts]: the `action: 'failed',` should be `closed` here, right? Or there any change for this particular event?

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 4]
```diff
@@ -43,15 +44,17 @@ export class SubscribeToLiveAgent {
 			.then(async (response) => {
 				if (response.statusCode === 403) {
 					console.log(ErrorLogs.LIVEAGENT_SESSION_EXPIRED);
-					await handleEndChatCallback.handleEndChat();
+					this.modify.getAnalytics().sendEvent(getEventData(this.data.room.id, EventName.LIVEAGENT_SESSION_EXPIRED));
+					await handleEndChatCallback.handleEndChat(CloseMessages.LIVEAGENT_SESSION_EXPIRED);
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: Can we move this `sendEvent` inside `handleEndChat` function? So that it sends the event when the chat is actually closed. 

Something like to this https://github.com/WideChat/Apps.Salesforce.LiveAgent/blob/master/handlers/InitiateSalesforceSessionHandler.ts#L110...L121

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 5]
```diff
@@ -69,24 +72,37 @@ export class SubscribeToLiveAgent {
 						if (chatEndedReason === 'agent') {
 							await updateRoomCustomFields(this.data.room.id, { agentEndedChat: true }, this.read, this.modify);
 							this.modify.getAnalytics().sendEvent(getEventData(this.data.room.id, EventName.CHAT_CLOSED_BY_AGENT));
+							await handleEndChatCallback.handleEndChat(CloseMessages.CLOSED_BY_AGENT);
+						} else {
+							const event = getEventData(this.data.room.id, EventName.CHAT_CLOSED_BY_UNDEFINED_REASON);
+							if (event?.properties) {
+								event.properties.close_method = chatEndedReason;
+							}
+							this.modify.getAnalytics().sendEvent(event);
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: For this event, When the chat is closed by the visitor, we receive the reason `visitor` in pullMessages.

When the visitor closes the chat we send an event from the widget. After that, the salesforce case is closed with the reason `visitor` and we receive the `ChatEnded` message as a part of pullMessages. So it will again send the duplicate event.

Same case with timeout

**Review by Shailesh351 — COMMENTED** [review]
@ear-dev FYI this PR adds new `Chat closed` events that were not covered earlier.

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts (hunk 5 above)
Comment (AlexanderKanakis) [reply helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: So this event is redundant?

Comment (Shailesh351) [reply helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: We definitely want ChatEnded by agent event, and the widget sends chat closed by the visitor so we don't need to send it from SF. If there are any other reasons from the salesforce for chat close we need to cover those

File: helperFunctions/subscribeHelpers/InitiateSalesforceSessionHelpers/CheckAgentStatusCallback.ts [hunk 6]
```diff
@@ -40,7 +40,7 @@ export class CheckAgentStatusCallback {
 			this.technicalDifficultyMessage,
 		);
 
-		await handleEndChatCallback.handleEndChat();
+		await handleEndChatCallback.handleEndChat(error);
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/InitiateSalesforceSessionHelpers/CheckAgentStatusCallback.ts]: We are not sending the event in this case?

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/HandleEndChatCallback.ts [hunk 7]
```diff
@@ -23,7 +25,11 @@ export class HandleEndChatCallback {
 		private technicalDifficultyMessage: string,
 	) {}
 
-	public handleEndChat = async () => {
+	public handleEndChat = async (closeMessage?: string, event?: EventName) => {
+		if (event) {
+			this.modify.getAnalytics().sendEvent(getEventData(this.data.room.id, event));
+		}
+
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/HandleEndChatCallback.ts]: I see handleEndChat is called with the event for a couple of cases. In we can't cover all the case, maybe we should keep it separate?

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 8]
```diff
@@ -69,24 +76,37 @@ export class SubscribeToLiveAgent {
 						if (chatEndedReason === 'agent') {
 							await updateRoomCustomFields(this.data.room.id, { agentEndedChat: true }, this.read, this.modify);
 							this.modify.getAnalytics().sendEvent(getEventData(this.data.room.id, EventName.CHAT_CLOSED_BY_AGENT));
+							await handleEndChatCallback.handleEndChat(CloseMessages.CLOSED_BY_AGENT);
+						} else if (chatEndedReason !== 'client') {
+							const event = getEventData(this.data.room.id, EventName.CHAT_CLOSED_BY_UNDEFINED_REASON);
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: Why do have an `undefined` reason here? Can you check for possible reasons and add those instead?

**Review by Shailesh351 — COMMENTED** [review]
There are places when the session expired but the event is missing. `handlers/LiveAgentSessionHandler.ts` `helperFunctions/subscribeHelpers/InitiateSalesforceSessionHelpers/CheckChatStatusHelper.ts`

Same for UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE, you can global search for `UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE`
in `helperFunctions/subscribeHelpers/InitiateSalesforceSessionHelpers/CheckChatStatusHelper.ts` `handlers/InitiateSalesforceSessionHandler.ts`

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/HandleEndChatCallback.ts (hunk 7 above)
Comment (AlexanderKanakis) [reply helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/HandleEndChatCallback.ts]: Yup, I tried handling this issue https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/75#discussion_r982043352 but I didn't consider the error cases. I will revert it to separate event sending.

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts (hunk 8 above)
Comment (AlexanderKanakis) [reply helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: Do we have an Enum of reasons? I'm trying to find where we set this parameter.

Comment (Shailesh351) [reply helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: It comes from Salesforce API

**Comment by AlexanderKanakis** [comment]
https://github.com/WideChat/Apps.Salesforce.LiveAgent/blob/64441013aa83e6bfc0a4ed470d7c2857293190ff/helperFunctions/subscribeHelpers/InitiateSalesforceSessionHelpers/CheckChatStatusHelper.ts#L171 
I think that this block will never be executed.

File: helperFunctions/subscribeHelpers/InitiateSalesforceSessionHelpers/CheckChatStatusHelper.ts [hunk 9]
```diff
@@ -161,15 +174,20 @@ export class CheckChatStatus {
...
 							await this.checkCurrentChatStatus();
 						} else {
-							await checkAgentStatusDirectCallback.checkAgentStatusCallbackError(this.technicalDifficultyMessage);
+							await checkAgentStatusDirectCallback.checkAgentStatusCallbackError(
+								ErrorLogs.UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE,
+								EventName.CHAT_CLOSED_UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE,
+							);
 							return;
 						}
 					}
```
Comment (AlexanderKanakis) [inline helperFunctions/subscribeHelpers/InitiateSalesforceSessionHelpers/CheckChatStatusHelper.ts]: I think that this block will never be executed.

File: enum/Analytics.ts [hunk 10]
```diff
@@ -4,10 +4,22 @@ export enum EventName {
 	ESCALATION_FAILED_DUE_TO_NO_LIVEAGENT_AVAILABLE = 'escalation_failed_due_to_no_liveagent_available',
 	ESCALATION_FAILED_DUE_TO_SALESFORCE_ERROR = 'escalation_failed_due_to_salesforce_error',
 	ESCALATION_FAILED_DUE_TO_NETWORK_OR_APP_ERROR = 'escalation_failed_due_to_network_or_app_error',
+	ESCALATION_FAILED_DUE_TO_LIVEAGENT_SESSION_ID_GENERATION_ERROR = 'escalation_failed_due_to_liveagent_session_id_generation_error',
+	ESCALATION_FAILED_DUE_TO_LIVEAGENT_CHAT_REQUEST_ERROR = 'escalation_failed_due_to_livechat_agent_response_error',
+	ESCALATION_FAILED_DUE_TO_LIVEAGENT_RESPONSE_CHECKING_ERROR = 'escalation_failed_due_to_liveagent_response_checking_error',
```
Comment (Shailesh351) [inline enum/Analytics.ts:9]: This event is not being sent anyewhere. Can we remove it if not needed?

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 11]
```diff
@@ -69,24 +73,44 @@ export class SubscribeToLiveAgent {
...
+							await handleEndChatCallback.handleEndChat(CloseMessages.CLOSED_BY_VISITOR);
 						}
-						await handleEndChatCallback.handleEndChat();
+					} else if (isChatRequestFail === true) {
+						const {
+							message: { reason: chatEndedReason },
+						} = getForEvent(messageArray, 'ChatRequestFail');
+						if (chatEndedReason === 'Unavailable') {
+							await updateRoomCustomFields(this.data.room.id, { agentDisconnected: true }, this.read, this.modify);
+							this.modify.getAnalytics().sendEvent(getEventData(this.data.room.id, EventName.CHAT_CLOSED_LIVEAGENT_DISCONNECTED));
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: At other places, we are sending `ESCALATION_FAILED_DUE_TO_NO_LIVEAGENT_AVAILABLE` when we receive an `Unavailable` message. here we are sending `CHAT_CLOSED_LIVEAGENT_DISCONNECTED`

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 12]
```diff
@@ -69,24 +73,44 @@ export class SubscribeToLiveAgent {
...
+							await handleEndChatCallback.handleEndChat(CloseMessages.LIVEAGENT_DISCONNECTED);
+						}
+						const event = getEventData(this.data.room.id, EventName.CHAT_CLOSED_UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE);
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: Two events are being sent in this block. this one and the above one. I think we need only one?

File: lib/DialogflowAgentAssignedHandler.ts [hunk 13]
```diff
@@ -76,6 +76,9 @@ export class DialogflowAgentAssignedClass {
 				} else if (customFields && customFields.errorSession === true && dialogflowSessionErrorEventName) {
 					console.log(ErrorLogs.DIALOGFLOW_ERROR_SESSION);
 					eventParams.name = dialogflowSessionErrorEventName;
+				} else if (customFields && customFields.agentDisconnected === true && dialogflowSessionErrorEventName) {
+					console.log(InfoLogs.LIVEAGENT_DISCONNECTED);
+					eventParams.name = dialogflowAgentUnavailableEventName;
```
Comment (Shailesh351) [inline lib/DialogflowAgentAssignedHandler.ts]: If this `agentDisconnected` makes confusion with `agentUnavailable` we can refactor customField name

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts (hunk 11 above)
Comment (AlexanderKanakis) [reply helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: This event is specifically sent after we have escalated to a liveagent successfully. We can send `ESCALATION_FAILED_DUE_TO_NO_LIVEAGENT_AVAILABLE `, but I thought that `CHAT_CLOSED_LIVEAGENT_DISCONNECTED` is a bit more specific.

Comment (Shailesh351) [reply helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: I think we have a specific message type for `AgentDisconnect`  and Unavailable is specific to when there is no agent online

There is a separate story to handle AgentDisconnect https://github.com/WideChat/Rocket.Chat/issues/1316

**Comment by ear-dev** [comment]
@Shailesh351 after Alexander merges the 78 changes into this PR please have another look.  thanks.

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 14]
```diff
@@ -69,24 +73,42 @@ export class SubscribeToLiveAgent {
...
-						await handleEndChatCallback.handleEndChat();
+					} else if (isChatRequestFail === true) {
+						const {
+							message: { reason: chatEndedReason },
+						} = getForEvent(messageArray, 'ChatRequestFail');
+						if (chatEndedReason === 'Unavailable') {
+							await updateRoomCustomFields(this.data.room.id, { agentUnavailable: true }, this.read, this.modify);
+							this.modify.getAnalytics().sendEvent(getEventData(this.data.room.id, EventName.CHAT_CLOSED_LIVEAGENT_DISCONNECTED));
+							await handleEndChatCallback.handleEndChat(CloseMessages.LIVEAGENT_DISCONNECTED);
+						}
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: At other places, we are sending `ESCALATION_FAILED_DUE_TO_NO_LIVEAGENT_AVAILABLE` when we receive an `Unavailable` message. here we are sending `CHAT_CLOSED_LIVEAGENT_DISCONNECTED`

Also close chat message is live agent disconnect, it should be agent unavailable

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 15]
```diff
@@ -69,24 +73,42 @@ export class SubscribeToLiveAgent {
...
+						await handleEndChatCallback.handleEndChat(CloseMessages.UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE);
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: When `chatEndedReason === 'Unavailable'` we are calling handleChat, and this one is being called every time. We should only call handleEndChat only once when `chatEndedReason === 'Unavailable'`  right?

**Comment by AlexanderKanakis** [comment]
Merged #78 to #75 . Ready to review.

File: enum/Analytics.ts [hunk 16]
```diff
@@ -55,6 +75,60 @@ export const Events: Record<string, IAnalyticsEvent> = {
 			sf_chat_key: '',
 		},
 	},
+	[EventName.FAILURE_GETTING_SF_MESSAGES]: {
```
Comment (Shailesh351) [inline enum/Analytics.ts]: Can we rename the event name here similar to other errors with prefix `ESCALATION_FAILED_DUE....`

File: enum/Analytics.ts [hunk 17]
```diff
@@ -77,4 +151,36 @@ export const Events: Record<string, IAnalyticsEvent> = {
...
+	},
+	[EventName.CHAT_CLOSED_UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE]: {
+		category: EventCatagory.CHAT_SESSION,
+		eventType: EventType.SESSION,
+		action: 'closed',
+		properties: {
+			close_method: '',
+		},
+	},
+	[EventName.EMPTY_MESSAGE_FROM_LIVEAGENT]: {
```
Comment (Shailesh351) [inline enum/Analytics.ts]: Can we rename event name here with prefix `CHAT_CLOSED_ ....` similar to other chat closed events?

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 18]
```diff
@@ -69,24 +75,50 @@ export class SubscribeToLiveAgent {
 						if (chatEndedReason === 'agent') {
 							await updateRoomCustomFields(this.data.room.id, { agentEndedChat: true }, this.read, this.modify);
 							this.modify.getAnalytics().sendEvent(getEventData(this.data.room.id, EventName.CHAT_CLOSED_BY_AGENT));
+							await handleEndChatCallback.handleEndChat(CloseMessages.CLOSED_BY_AGENT);
+						} else {
+							await handleEndChatCallback.handleEndChat(CloseMessages.CLOSED_BY_VISITOR);
+						}
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: I think the previous issue with redundant chat closed by visitor is back again after you merged #78 ?

https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/75#discussion_r982047342

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts [hunk 19]
```diff
@@ -69,24 +75,50 @@ export class SubscribeToLiveAgent {
...
 			})
 			.catch(async (error) => {
-				console.error(ErrorLogs.UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE, error);
-				await handleEndChatCallback.handleEndChat();
+				const event = getEventData(this.data.room.id, EventName.FAILURE_GETTING_SF_MESSAGES);
+				if (event?.properties) {
+					event.properties.reason = error;
+				}
+				this.modify.getAnalytics().sendEvent(event);
+				console.error(ErrorLogs.FAILURE_GETTING_SF_MESSAGES, error);
```
Comment (Shailesh351) [inline helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: Here `event.properties.reason = error;` reason should be some static value, right? something like `failure getting SF messages`

If we pass an error, it can contain roomId which changes every time. So it will not appear in grafana correctly. It will just create thousands of different reasons why the session closed.(Imagine the pie chart it will create 😅 ) This event will not be that frequent but still.

File: helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts (hunk 18 above)
Comment (AlexanderKanakis) [reply helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubscribeToLiveAgentHelper.ts]: Good catch, thanks

File: enum/Analytics.ts [hunk 20]
```diff
@@ -4,10 +4,22 @@ export enum EventName {
...
+	ESCALATION_FAILED_DUE_TO_INVALID_APP_CONFIGURATION = 'escalation_failed_due_to_invalid_app_configuration',
 	ESCALATION_SUCCESSFUL = 'escalation_successful',
 	AGENT_TRANSFER_SUCCESSFUL = 'agent_transfer_successful',
 	CHAT_CLOSED_BY_AGENT = 'chat_closed_by_agent',
 	CHAT_CLOSED_BY_TIMEOUT = 'chat_closed_by_timeout',
+	CHAT_CLOSED_LIVEAGENT_SESSION_EXPIRED = 'chat_closed_live_agent_session_expired',
+	CHAT_CLOSED_LIVEAGENT_DISCONNECTED = 'chat_closed_live_agent_disconnected',
+	CHAT_CLOSED_UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE = 'chat_closed_unknown_error_in_checking_agent_response',
+	ESCALATION_FAILED_DUE_TO_ERROR_GETTING_SF_MESSAGES = 'escalation_failed_due_to_error_getting_sf_messages',
+	SALESFORCE_CHAT_API_NOT_FOUND = 'salesforce_chat_api_not_found',
```
Comment (Shailesh351) [inline enum/Analytics.ts]: If this is an escalation error can we include prefixes, please?

File: enum/Analytics.ts [hunk 21]
```diff
@@ -55,6 +75,60 @@ export const Events: Record<string, IAnalyticsEvent> = {
 			sf_chat_key: '',
 		},
 	},
+	[EventName.ESCALATION_FAILED_DUE_TO_ERROR_GETTING_SF_MESSAGES]: {
+		category: EventCatagory.ESCALATION,
+		eventType: EventType.SESSION,
+		action: 'failed',
+		properties: {},
+	},
```
Comment (Shailesh351) [inline enum/Analytics.ts]: I think we missed `faliure_reason` here. Or Is this even an escalation error? we are calling it in checkCurrentChatStatus.

File: enum/Analytics.ts [hunk 22]
```diff
@@ -4,10 +4,22 @@ export enum EventName {
...
+	ESCALATION_FAILED_DUE_TO_LIVEAGENT_RESPONSE_ERROR = 'escalation_failed_due_to_liveagent_response_error',
+	ESCALATION_FAILED_DUE_TO_SALESFORCE_INTERNAL_FAILURE = 'escalation_due_to_salesforce_internal_failure',
+	ESCALATION_FAILED_DUE_TO_INVALID_APP_CONFIGURATION = 'escalation_failed_due_to_invalid_app_configuration',
 	ESCALATION_SUCCESSFUL = 'escalation_successful',
 	AGENT_TRANSFER_SUCCESSFUL = 'agent_transfer_successful',
 	CHAT_CLOSED_BY_AGENT = 'chat_closed_by_agent',
 	CHAT_CLOSED_BY_TIMEOUT = 'chat_closed_by_timeout',
+	CHAT_CLOSED_LIVEAGENT_SESSION_EXPIRED = 'chat_closed_live_agent_session_expired',
+	CHAT_CLOSED_LIVEAGENT_DISCONNECTED = 'chat_closed_live_agent_disconnected',
+	CHAT_CLOSED_UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE = 'chat_closed_unknown_error_in_checking_agent_response',
```
Comment (Shailesh351) [inline enum/Analytics.ts:19]: `close_method` property is empty while sending the event `CHAT_CLOSED_UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE `

**Comment by Shailesh351** [comment]
@ear-dev I have added the new events in the wiki which are included in this PR https://github.com/WideChat/Rocket.Chat/wiki/SNS-Logger/_compare/1eee89aad850ee3957c4365c51ec687f61f41002

File: enum/Analytics.ts (hunk 21 above)
Comment (AlexanderKanakis) [reply enum/Analytics.ts]: And SubscribeToLiveAgentHelper. Sends even when we are not able to pull messages for SF. Do we want an event for that?

Comment (Shailesh351) [reply enum/Analytics.ts]: If it fails the escalation or closes the chat then yes

**Comment by ear-dev** [comment]
> @ear-dev I have added the new events in the wiki which are included in this PR https://github.com/WideChat/Rocket.Chat/wiki/SNS-Logger/_compare/1eee89aad850ee3957c4365c51ec687f61f41002

That's awesome!  Thanks @Shailesh351

**Review by Shailesh351 — APPROVED** [review]
Thanks, Alexander!

**Comment by ear-dev** [comment]
@AlexanderKanakis I tested a case where the Salesforce agent went offline mid chat, and the 'Conversation Closed' system message is not correct.  It is showing the contents of the sf.app config entry for "No Live Agent Available Message *"

Can you take a look please?  thanks...

image

**Comment by ear-dev** [comment]
@AlexanderKanakis I tested a case where I mangled the SF url in the admin UI.  What happened is that I get the proper Conversation Closed message, but that same message is also now sent to the visitor in the chat window, instead of the expected "Technical Difficulty Message *" as configured in the SF admin UI. 

Can you take a look please?  thanks. 

image

**Comment by AlexanderKanakis** [comment]
> @AlexanderKanakis I tested a case where I mangled the SF url in the admin UI. What happened is that I get the proper Conversation Closed message, but that same message is also now sent to the visitor in the chat window, instead of the expected "Technical Difficulty Message *" as configured in the SF admin UI.
> 
> Can you take a look please? thanks.
> 
> image

@ear-dev do you happen to have debug messages activated?

**Comment by ear-dev** [comment]
@AlexanderKanakis making a note here of what we just discussed....

It seems to me like you may have some wires crossed.  Please go back over the entire PR and distinguish properly between messages sent to the visitor and messages that are only meant to show up as system messages for the admin under "conversation closed".   

The messages meant for the visitor are most often configured in the app.admin.ui 

Thanks.

**Comment by AlexanderKanakis** [comment]
The issue was caused by our error callback function. The error description was used both for the admin UI close message and the client message.  

Additionally, when the chat was ended by non-error reasons, the client did not get a specific technical issues, or no agents available, message before the end chat message. Both are fixed with new commit.

**Comment by ear-dev** [comment]
thanks @AlexanderKanakis this is now working as expected.
